name: Deploy to EC2 ðŸš€

on:
  push:
    branches:
      - "dev"  # This triggers the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current branch
      - name: Checkout current branch âœ…
        uses: actions/checkout@v3

      # Step 2: Set up SSH key and whitelist EC2 IP address
      - name: Set up SSH key and whitelist EC2 IP address ðŸ»â€â„ï¸
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: SSH into EC2 and create the target directory
      - name: SSH into EC2 and create target directory ðŸš€
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            mkdir -p /home/ubuntu/Social-Media-Management-Application
          "

      # Step 4: Copy files to remote server
      - name: Copy files to remote server ðŸš™
        run: |
          scp -r * ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/Social-Media-Management-Application/

      # Step 5: SSH into EC2 instance, pull latest code, and deploy Docker container
      - name: SSH into EC2 and deploy Docker container ðŸš€
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/Social-Media-Management-Application
            sudo git pull origin main
            # Start Redis container
            sudo docker stop redis || true
            sudo docker rm redis || true
            sudo docker run -d --name redis -p 6379:6379 redis
            sudo docker build -t my-python-app -f Dockerfile .
            sudo docker stop my-python-app || true
            sudo docker rm my-python-app || true
            sudo docker run -d --name my-python-app -p 8000:8000 my-python-app
          "

      # Step 6: Clean up SSH key
      - name: Clean up SSH key ðŸš€
        if: always()
        run: rm -f ~/.ssh/id_rsa
